site: social trails
date: 2020-07-31
title: Social Trails to Close at Seward Park
centerLat: 47.555
centerLon: -122.2512
initialZoom: 15

points:

  - name: st1.1
    observer: PTS
    group: social trails
    date: 2020-07-27
    lon: -122.2508 
    lat: 47.56103
    color: red
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/socialTrailClosing/st1.html

  - name: st1.2
    observer: PTS
    group: social trails
    date: 2020-07-27
    lon: -122.2507 
    lat: 47.56108
    color: red
    radius: 2
    details: http://pshannon.net/swordFerns/snoq/pts1.html

  - name: st1.3
    observer: PTS
    group: social trails
    date: 2020-07-27
    lon: -122.2508 
    lat: 47.56107
    color: red
    radius: 2
    details: http://pshannon.net/swordFerns/snoq/pts1.html

  - name: st1.4
    observer: PTS
    group: social trails
    date: 2020-07-27
    lon: -122.2507 
    lat: 47.56109
    color: red
    radius: 2
    details: http://pshannon.net/swordFerns/snoq/pts1.html

  - name: st2.1
    observer: PTS
    group: social trails
    date: 2020-07-31
    lon: -122.2518
    lat: 47.56140
    color: red
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/socialTrailClosing/st2.html

  - name: st2.2
    observer: PTS
    group: social trails
    date: 2020-07-31
    lon: -122.2516 
    lat: 47.56151
    color: red
    radius: 2
    details: http://pshannon.net/swordFerns/snoq/pts1.html

  - name: st2.3
    observer: PTS
    group: social trails
    date: 2020-07-31
    lon: -122.2515
    lat: 47.56153
    color: red
    radius: 2
    details: http://pshannon.net/swordFerns/snoq/pts1.html

  - name: st2.4
    observer: PTS
    group: social trails
    date: 2020-07-31
    lon: -122.2516
    lat: 47.56148
    color: red
    radius: 2
    details: http://pshannon.net/swordFerns/snoq/pts1.html
