DEST=paulshannnon@pshannon.net:public_html/pshannon.net/sewardParkRestoration/barmitzvah/

default:  html

html:
	scp *.html $(DEST)

jpg: jpeg

jpeg:
	scp *.jpg $(DEST)
	scp *.jpeg $(DEST)

all: html jpg



