#FROM rocker/shiny
FROM map_app_31jul2020
WORKDIR /home/shiny
COPY webapp.R .
COPY site.yaml .
#COPY installPrerequisites.R .
#RUN R -f installPrerequisites.R
#COPY pkgs/igvShiny_0.99.91.tar.gz .
#COPY pkgs/shinyModules_1.0.13.tar.gz .
#RUN R CMD INSTALL igvShiny_0.99.91.tar.gz
#RUN R CMD INSTALL shinyModules_1.0.13.tar.gz



