site: Seward Park
date: 2020-08-08
title: Magnficent Forest - Damage and Repair 
centerLat: 47.556656
centerLon: -122.250784
initialZoom: 15

points:

  - name: Salal Decline 001
    id: id_001
    observer: PTS
    group: salal decline?
    date: 2020-08-12
    lat: 47.559997
    lon: -122.250396
    color: grey
    radius: 6
    details: http://pshannon.net/sewardParkRestoration/salalDecline_001


  - name: Woodpecker Trail, multi-rooted maple
    id: id_002
    observer: CMA
    group: overuse
    date: 2020-08-12
    lat:  47.553538
    lon: -122.251254
    color: red
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/woodpeckerTrail_multirootedTree

  - name: Woodpecker Trail, Stone Steps
    id: id_003
    observer: CMA
    group: overuse
    date: 2020-08-12
    lat: 47.554008
    lon: -122.251148
    color: red
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/woodpeckerTrail_steps


  - name: Fairy Tree
    id: id_004
    observer: PTS
    group: Fairy Tree
    date: 2020-08-08
    lat:  47.552852
    lon: -122.251255
    color: red
    radius: 6
    #details: http://localhost:9999/fairyTree
    details: http://pshannon.net/sewardParkRestoration/fairyTree

  - name: "Social Trail #1"
    id: id_005
    observer: PTS
    group: social trails
    date: 2020-07-27
    lat: 47.560973
    lon: -122.250910
    color: red
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/socialTrail_001


  - name: "Social Trail #2"
    id: id_006
    observer: PTS
    group: social trails
    date: 2020-07-31
    lat: 47.561301
    lon: -122.251884
    color: red
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/socialTrail_002

  - name: "Social Trail #3"
    id: id_007
    observer: PTS
    group: social trails
    date: 2020-07-31
    lat: 47.561412
    lon: -122.252411
    color: red
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/socialTrail_003_northeast

  - name: "Social Trail #4"
    id: id_008
    observer: PTS
    group: social trails
    date: 2020-07-31
    lat: 47.561361
    lon: -122.252173
    color: red
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/socialTrail_004_northeast

  - name: "Social Trail #5"
    id: id_009
    observer: PTS
    group: social trails
    date: 2020-07-31
    lat: 47.561331
    lon: -122.252030
    color: red
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/socialTrail_005_northeast

  - name: Bar Mitzvah Destruction
    id: id_010
    observer: PTS
    group: clearings
    date: 2020-07-13
    lat: 47.555469
    lon: -122.251670
    color: blue
    radius: 6
    details: http://pshannon.net/sewardParkRestoration/barmitzvah


  - name: HBB removal experiment
    id: id_011
    observer: PTS
    group: restorations
    date: 2020-08-08
    lat: 47.552363
    lon: -122.256431
    color: green
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/andrewsBayHBBexperiment

  - name: cherry snag
    id: id_012
    observer: PTS
    group: snags
    date: 2020-08-08
    lat: 47.552289
    lon: -122.256477
    color: brown
    radius: 2
    details: nop

  - name: cedar snag
    id: id_013
    observer: PTS
    group: snags
    date: 2020-08-08
    lat: 47.552258
    lon: -122.256310
    color: brown
    radius: 2
    details: nop

  - name: cistern graffiti
    id: id_014
    observer: PTS
    group: grafitti
    date: 2020-09-26
    lat: 47.555406
    lon: -122.250561
    color: brown
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/cisternAtJunction

  - name: High ground die-off
    id: id_015
    observer: PTS
    group: new 2020 die-off
    date: 2020-10-02
    lat: 47.556631
    lon: -122.251311
    color: black
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/highGroundFernDieoff

  - name: tree.036
    observer: PTS
    id: dougFir.36
    group: old doug firs
    date: 2020-10-17
    lon: -122.2526
    lat: 47.56166
    color: black
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/dougFir.036

  - name: tree.037
    observer: PTS
    id: waypoint.37
    group: old doug firs
    date: 2020-10-17
    lon: -122.2521
    lat: 47.56164
    color: black
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/dougFir.037

  - name: tree.038
    observer: PTS
    id: waypoint.38
    group: old doug firs
    date: 2020-10-17
    lon: -122.2518
    lat:  47.56173
    color: black
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/dougFir.038

  - name: tree.039
    observer: PTS
    id: waypoint.39
    group: old doug firs
    date: 2020-10-17
    lat: 47.560721
    lon: -122.250737
    color: black
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/dougFir.039

  - name: tree.040
    observer: PTS
    id: waypoint.40
    group: old doug firs
    date: 2020-10-17
    lon: -122.2501
    lat: 47.55988
    color: brown
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/dougFir.040


  - name: tree.041
    observer: PTS
    id: waypoint.41
    group: old doug firs
    date: 2020-10-17
    lon: -122.2497
    lat: 47.56016
    color: black
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/dougFir.041

  - name: tree.042
    observer: PTS
    id: waypoint.42
    group: old doug firs
    date: 2020-10-17
    lon: -122.2494
    lat: 47.55996
    color: brown
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/dougFir.042


  - name: tree.043
    observer: PTS
    id: waypoint.43
    group: old doug firs
    date: 2020-10-25
    lon: -122.24874
    lat: 47.55229
    color: black
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/dougFir.042


  - name: tree.044
    observer: PTS
    id: waypoint.44
    group: old doug firs
    date: 2020-10-25
    lon: -122.25169
    lat: 47.55611
    color: black
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/dougFir.042


  - name: tree.045
    observer: PTS
    id: waypoint.45
    group: old doug firs
    date: 2020-10-25
    lon: -122.25197
    lat: 47.55722
    color: black
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/dougFir.042


  - name: tree.046
    observer: PTS
    id: waypoint.46
    group: old doug firs
    date: 2020-10-25
    lon: -122.25033
    lat: 47.55973
    color: black
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/dougFir.042




#  - name: clearing start
#    observer: PTS
#    group: clearings
#    date: 2020-07-13
#    lat: 47.554905
#    lon: -122.251418
#    color: blue
#    radius: 2
#    details: http://pshannon.net/sewardParkRestoration/socialTrailClosing/st2.html
#
#  - name: clearing elbow
#    observer: PTS
#    group: clearings
#    date: 2020-07-13
#    lat: 47.555379
#    lon: -122.251407
#    color: blue
#    radius: 2
#    details: http://pshannon.net/sewardParkRestoration/socialTrailClosing/st2.html
#
