site: Seward Park
date: 2020-08-08
title: Magnficent Forest - Damage and Repair 
centerLat: 47.556656
centerLon: -122.250784
initialZoom: 15

points:

  - name: Salal Decline 001
    observer: PTS
    group: salal decline?
    date: 2020-08-12
    lat: 47.559997
    lon: -122.250396
    color: brown
    radius: 6
    details: http://pshannon.net/sewardParkRestoration/salalDecline_001


  - name: Woodpecker Trail, multi-rooted maple
    observer: CMA
    group: overuse
    date: 2020-08-12
    lat:  47.553538
    lon: -122.251254
    color: red
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/woodpeckerTrail_multirootedTree

  - name: Woodpecker Trail, Stone Steps
    observer: CMA
    group: overuse
    date: 2020-08-12
    lat: 47.554008
    lon: -122.251148
    color: red
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/woodpeckerTrail_steps


  - name: Fairy Tree
    observer: PTS
    group: Fairy Tree
    date: 2020-08-08
    lat:  47.552852
    lon: -122.251255
    color: red
    radius: 6
    #details: http://localhost:9999/fairyTree
    details: http://pshannon.net/sewardParkRestoration/fairyTree

  - name: "Social Trail #1"
    observer: PTS
    group: social trails
    date: 2020-07-27
    lat: 47.560973
    lon: -122.250910
    color: red
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/socialTrail_001


  - name: "Social Trail #2"
    observer: PTS
    group: social trails
    date: 2020-07-31
    lat: 47.561301
    lon: -122.251884
    color: red
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/socialTrail_002

  - name: "Social Trail #3"
    observer: PTS
    group: social trails
    date: 2020-07-31
    lat: 47.561453
    lon: -122.252394
    color: red
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/socialTrail_002

  - name: "Social Trail #4"
    observer: PTS
    group: social trails
    date: 2020-07-31
    lat: 47.561388
    lon: -122.252158
    color: red
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/socialTrail_002

  - name: "Social Trail #5"
    observer: PTS
    group: social trails
    date: 2020-07-31
    lat: 47.561341
    lon: -122.252024
    color: red
    radius: 2
    details: http://pshannon.net/sewardParkRestoration/socialTrail_002

  - name: Bar Mitzvah Destruction
    observer: PTS
    group: clearings
    date: 2020-07-13
    lat: 47.555469
    lon: -122.251670
    color: blue
    radius: 6
    details: http://pshannon.net/sewardParkRestoration/barmitzvah


  - name: HBB removal experiment
    observer: PTS
    group: restorations
    date: 2020-08-08
    lat: 47.552363
    lon: -122.256431
    color: green
    radius: 4
    details: http://pshannon.net/sewardParkRestoration/andrewsBayHBBexperiment

  - name: cherry snag
    observer: PTS
    group: snags
    date: 2020-08-08
    lat: 47.552289
    lon: -122.256477
    color: brown
    radius: 2
    details: nop

  - name: cedar snag
    observer: PTS
    group: snags
    date: 2020-08-08
    lat: 47.552258
    lon: -122.256310
    color: brown
    radius: 2
    details: nop


#  - name: clearing start
#    observer: PTS
#    group: clearings
#    date: 2020-07-13
#    lat: 47.554905
#    lon: -122.251418
#    color: blue
#    radius: 2
#    details: http://pshannon.net/sewardParkRestoration/socialTrailClosing/st2.html
#
#  - name: clearing elbow
#    observer: PTS
#    group: clearings
#    date: 2020-07-13
#    lat: 47.555379
#    lon: -122.251407
#    color: blue
#    radius: 2
#    details: http://pshannon.net/sewardParkRestoration/socialTrailClosing/st2.html
#