site: Seward Park
date: 2020-08-08
title: Magnficent Forest - Damage and Repair 
centerLat: 47.556656
centerLon: -122.250784
initialZoom: 15
initialGroups: ["Hemlock Decline"]
points:

# hemlock decline study starts here

  - name: hemlock.001
    observer: pshannon
    id: waypoint.140
    group: Hemlock Decline
    date: '2021-07-05'
    lat: 47.558333
    lon: -122.250825
    color: grey
    radius: 9.0
    details: NA
  - name: hemlock.002
    observer: all
    id: waypoint.144
    group: Hemlock Decline
    date: '2021-07-14'
    lat: 47.55855
    lon: -122.25139
    color: green
    radius: 9.0
    details: NA
  - name: hemlock.003
    observer: all
    id: waypoint.145
    group: Hemlock Decline
    date: '2021-07-14'
    lat: 47.558316
    lon: -122.250828
    color: grey
    radius: 18.0
    details: NA
  - name: hemlock.004
    observer: all
    id: waypoint.146
    group: Hemlock Decline
    date: '2021-07-14'
    lat: 47.55785
    lon: -122.25077
    color: grey
    radius: 9.0
    details: NA
  - name: hemlock.005
    observer: all
    id: waypoint.147
    group: Hemlock Decline
    date: '2021-07-14'
    lat: 47.557763
    lon: -122.250862
    color: black
    radius: 9.0
    details: NA
  - name: hemlock.006
    observer: all
    id: waypoint.148
    group: Hemlock Decline
    date: '2021-07-14'
    lat: 47.55779
    lon: -122.250823
    color: grey
    radius: 15.0
    details: NA
  - name: hemlock.007
    observer: all
    id: waypoint.149
    group: Hemlock Decline
    date: '2021-07-14'
    lat: 47.55788
    lon: -122.25083
    color: grey
    radius: 15.0
    details: NA
  - name: hemlock.008
    observer: all
    id: waypoint.150
    group: Hemlock Decline
    date: '2021-07-14'
    lat: 47.557862
    lon: -122.250839
    color: grey
    radius: 18.0
    details: NA
  - name: hemlock.009
    observer: all
    id: waypoint.151
    group: Hemlock Decline
    date: '2021-07-14'
    lat: 47.557847
    lon: -122.250935
    color: grey
    radius: 6.0
    details: NA
  - name: hemlock.010
    observer: all
    id: waypoint.152
    group: Hemlock Decline
    date: '2021-07-14'
    lat: 47.55812
    lon: -122.25134
    color: grey
    radius: 6.0
    details: NA
  - name: hemlock.014
    observer: all
    id: waypoint.153
    group: Hemlock Decline
    date: '2021-07-15'
    lat: 47.55804
    lon: -122.25145
    color: grey
    radius: 12.0
    details: NA
  - name: hemlock.015
    observer: all
    id: waypoint.154
    group: Hemlock Decline
    date: '2021-07-15'
    lat: 47.55792
    lon: -122.25169
    color: grey
    radius: 12.0
    details: NA
  - name: hemlock.016
    observer: all
    id: waypoint.162
    group: Hemlock Decline
    date: '2021-07-15'
    lat: 47.55784
    lon: -122.25197
    color: green
    radius: 6.0
    details: NA
  - name: hemlock.017
    observer: all
    id: waypoint.162
    group: Hemlock Decline
    date: '2021-07-15'
    lat: 47.55786
    lon: -122.25196
    color: green
    radius: 6.0
    details: NA
  - name: hemlock.018
    observer: all
    id: waypoint.162
    group: Hemlock Decline
    date: '2021-07-15'
    lat: 47.55788
    lon: -122.25195
    color: green
    radius: 6.0
    details: NA
  - name: hemlock.019
    observer: all
    id: waypoint.156
    group: Hemlock Decline
    date: '2021-07-15'
    lat: 47.55796
    lon: -122.25182
    color: green
    radius: 3.0
    details: NA
  - name: hemlock.025
    observer: all
    id: waypoint.161
    group: Hemlock Decline
    date: '2021-07-19'
    lat: 47.55797
    lon: -122.2514
    color: green
    radius: 3.0
    details: NA
  - name: hemlock.026
    observer: pshannon
    id: waypoint.163
    group: Hemlock Decline
    date: '2021-07-19'
    lat: 47.5577
    lon: -122.25167
    color: grey
    radius: 21.0
    details: NA
  - name: hemlock.027
    observer: all
    id: waypoint.164
    group: Hemlock Decline
    date: '2021-07-19'
    lat: 47.55772
    lon: -122.25148
    color: green
    radius: 9.0
    details: NA
  - name: hemlock.028
    observer: all
    id: waypoint.164
    group: Hemlock Decline
    date: '2021-07-19'
    lat: 47.5577
    lon: -122.2515
    color: green
    radius: 9.0
    details: NA
  - name: hemlock.029
    observer: all
    id: waypoint.164
    group: Hemlock Decline
    date: '2021-07-19'
    lat: 47.55765
    lon: -122.25153
    color: black
    radius: 12.0
    details: NA
  - name: hemlock.030
    observer: all
    id: waypoint.166
    group: Hemlock Decline
    date: '2021-07-10'
    lat: 47.55689
    lon: -122.25172
    color: green
    radius: 6.0
    details: NA
  - name: hemlock.031
    observer: all
    id: waypoint.166
    group: Hemlock Decline
    date: '2021-07-10'
    lat: 47.55688
    lon: -122.25171
    color: green
    radius: 9.0
    details: NA
  - name: hemlock.032
    observer: all
    id: waypoint.166
    group: Hemlock Decline
    date: '2021-07-10'
    lat: 47.55689
    lon: -122.2517
    color: green
    radius: 9.0
    details: NA
  - name: hemlock.033
    observer: all
    id: waypoint.166
    group: Hemlock Decline
    date: '2021-07-10'
    lat: 47.5569
    lon: -122.25171
    color: green
    radius: 9.0
    details: NA
  - name: hemlock.035
    observer: all
    id: waypoint.167
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.55674
    lon: -122.25144
    color: green
    radius: 6.0
    details: NA
  - name: hemlock.036
    observer: all
    id: waypoint.167
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.55673
    lon: -122.25143
    color: grey
    radius: 15.0
    details: NA
  - name: hemlock.037
    observer: all
    id: waypoint.167
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.55674
    lon: -122.25141
    color: grey
    radius: 12.0
    details: NA
  - name: hemlock.038
    observer: all
    id: waypoint.168
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.5569
    lon: -122.25131
    color: grey
    radius: 18.0
    details: NA
  - name: hemlock.039
    observer: all
    id: waypoint.169
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.55696
    lon: -122.25105
    color: grey
    radius: 12.0
    details: NA
  - name: hemlock.040
    observer: all
    id: waypoint.169
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.55696
    lon: -122.25105
    color: green
    radius: 12.0
    details: NA
  - name: hemlock.041
    observer: all
    id: waypoint.170
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.557048
    lon: -122.250969
    color: grey
    radius: 9.0
    details: NA
  - name: hemlock.042
    observer: all
    id: waypoint.170
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.557053
    lon: -122.250983
    color: grey
    radius: 15.0
    details: NA
  - name: hemlock.043
    observer: all
    id: waypoint.171
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.557215
    lon: -122.250998
    color: grey
    radius: 15.0
    details: NA
  - name: hemlock.044
    observer: all
    id: waypoint.171
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.557209
    lon: -122.250989
    color: black
    radius: 3.0
    details: NA
  - name: hemlock.045
    observer: all
    id: waypoint.171
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.557199
    lon: -122.250986
    color: black
    radius: 3.0
    details: NA
  - name: hemlock.046
    observer: all
    id: waypoint.172
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.55697
    lon: -122.25134
    color: green
    radius: 15.0
    details: NA
  - name: hemlock.047
    observer: all
    id: waypoint.173
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.556944
    lon: -122.251338
    color: red
    radius: 15.0
    details: NA
  - name: hemlock.048
    observer: all
    id: waypoint.173
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.556972
    lon: -122.251306
    color: red
    radius: 18.0
    details: NA
  - name: hemlock.049
    observer: all
    id: waypoint.173
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.556963
    lon: -122.25134
    color: red
    radius: 15.0
    details: NA
  - name: hemlock.050
    observer: all
    id: waypoint.173
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.556969
    lon: -122.251373
    color: red
    radius: 18.0
    details: NA
  - name: hemlock.051
    observer: all
    id: waypoint.173
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.556986
    lon: -122.251364
    color: red
    radius: 12.0
    details: NA
  - name: hemlock.052
    observer: all
    id: waypoint.173
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.556988
    lon: -122.251338
    color: red
    radius: 15.0
    details: NA
  - name: hemlock.053
    observer: all
    id: waypoint.173
    group: Hemlock Decline
    date: '2021-07-22'
    lat: 47.55697
    lon: -122.25134
    color: red
    radius: 15.0
    details: NA
  - name: hemlock.054
    observer: all
    id: waypoint.175
    group: Hemlock Decline
    date: '2021-07-26'
    lat: 47.55708
    lon: -122.25144
    color: grey
    radius: 9.0
    details: NA
  - name: hemlock.055
    observer: all
    id: waypoint.176
    group: Hemlock Decline
    date: '2021-07-27'
    lat: 47.55765
    lon: -122.25109
    color: green
    radius: 21.0
    details: NA
  - name: hemlock.056
    observer: all
    id: waypoint.177
    group: Hemlock Decline
    date: '2021-07-27'
    lat: 47.5577
    lon: -122.2511
    color: grey
    radius: 6.0
    details: NA
  - name: hemlock.057
    observer: all
    id: waypoint.177
    group: Hemlock Decline
    date: '2021-07-27'
    lat: 47.5577
    lon: -122.2511
    color: green
    radius: 9.0
    details: NA
  - name: hemlock.058
    observer: all
    id: waypoint.178
    group: Hemlock Decline
    date: '2021-07-27'
    lat: 47.5577
    lon: -122.25088
    color: grey
    radius: 6.0
    details: NA
  - name: hemlock.059
    observer: all
    id: waypoint.178
    group: Hemlock Decline
    date: '2021-07-27'
    lat: 47.5577
    lon: -122.25088
    color: grey
    radius: 9.0
    details: NA
  - name: hemlock.060
    observer: all
    id: waypoint.179
    group: Hemlock Decline
    date: '2021-07-29'
    lat: 47.55724
    lon: -122.25193
    color: green
    radius: 9.0
    details: NA
  - name: hemlock.061
    observer: all
    id: waypoint.180
    group: Hemlock Decline
    date: '2021-07-29'
    lat: 47.557259
    lon: -122.251957
    color: grey
    radius: 9.0
    details: NA
  - name: hemlock.062
    observer: all
    id: waypoint.180
    group: Hemlock Decline
    date: '2021-07-29'
    lat: 47.557282
    lon: -122.251935
    color: green
    radius: 6.0
    details: NA
  - name: hemlock.063
    observer: all
    id: waypoint.180
    group: Hemlock Decline
    date: '2021-07-29'
    lat: 47.557283
    lon: -122.251931
    color: green
    radius: 12.0
    details: NA
  - name: hemlock.064
    observer: all
    id: waypoint.180
    group: Hemlock Decline
    date: '2021-07-29'
    lat: 47.557214
    lon: -122.25193
    color: grey
    radius: 12.0
    details: NA
  - name: hemlock.065
    observer: all
    id: waypoint.180
    group: Hemlock Decline
    date: '2021-07-29'
    lat: 47.557201
    lon: -122.25193
    color: green
    radius: 18.0
    details: NA
  - name: hemlock.066
    observer: all
    id: waypoint.180
    group: Hemlock Decline
    date: '2021-07-29'
    lat: 47.55719
    lon: -122.251928
    color: grey
    radius: 12.0
    details: NA
