DEST = paulshannnon@pshannon.net:public_html/pshannon.net/proposals/

default:
	@echo publish
	@echo viewRemote

publish:
	scp hemlockStudyProposal.html $(DEST)
	scp *.jpg $(DEST)
	scp *.png $(DEST)

viewRemote:
	open https://pshannon.net/proposals/hemlockStudyProposal.html


