DEST=paulshannnon@pshannon.net:public_html/pshannon.net/sewardParkRestoration/fairyTree/

default: html
	scp 2020-07-19-beforeMulching/*.jpg $(DEST)
	scp 2020-07-23-afterMulching/*.jpg $(DEST)

html:
	scp *.html $(DEST)




