DEST=paulshannnon@pshannon.net:public_html/pshannon.net/sewardParkRestoration/woodpeckerTrail_multirootedTree/

default:  html

all: html jpg

html:
	scp *.html $(DEST)

jpg:
	- scp *.jpg $(DEST)
	- scp *.jpeg $(DEST)





