default:
	@echo publish
	@echo viewRemote

publish:
	scp roadmap.html paulshannnon@pshannon.net:public_html/pshannon.net/swordFernResearchRoadmap/index.html
	scp *.png paulshannnon@pshannon.net:public_html/pshannon.net/swordFernResearchRoadmap/

viewRemote:
	open https://pshannon.net/swordFernResearchRoadmap
