DEST = paulshannnon@pshannon.net:public_html/pshannon.net/forestResearch/

default:
	@echo publish


publish:
	scp *.html $(DEST)
	scp *.png  $(DEST)
	scp *.jpg  $(DEST)
	scp *.jpeg $(DEST)

open:
	open https://pshannon.net/forestResearch


